### ISSUE TITLE
1.12 and 1.14 crossplay incompatible

### ISSUE THREAD

**Issue by ethaniccc** [CuongZ/UNWDelicatedSoftware#1]
## Summary
I went on my laptop with windows 10 edition (1.14.30) and I tried joining with my android (I downgraded my Minecraft on my Android to 1.12.1). It gave Internal Server on pre-join.

## Pastebin Link(s)
Console Output: https://pastebin.com/QxjV7iH5

### Reason For Error
`ErrorException: "array_wand(): Array is empty" Line 90 in src/pocketmine/entity/Skin`

**Comment by dtcu0ng** [comment]
Thank for giving issue, please provide full console output and list of plugins installed on your server, and did you try a pure [Foxel](https://github.com/FoxelTeam/Foxel) software? If you not face this error on Foxel, tell me to know.

**Comment by dtcu0ng** [comment]
![image](https://user-images.githubusercontent.com/34135258/74583566-cdb79400-4ffa-11ea-81a4-44e37e3c9602.png)
Confirmed your issue. I'm working on to fix this problem.

**Comment by dtcu0ng** [comment]
Foxel has the same problem, so I'm contact to Foxel to reveal this. Thank for your report.

**Comment by dtcu0ng** [comment]
My fault when updated the source forgot the skin fix from Foxel. I released new release to fixed it. Please update the server software as fast as possible.

- Issue closed.

**Comment by dtcu0ng** [comment]
again, checked 1 more time, that's just fix the invisible of skin in 1.12, not included this bug. caught server log and sent to Foxel.
